### ISSUE TITLE
Forgot anything?

### ISSUE THREAD

**Issue by millette** [tomekwi/format-xml.cli#1]
Hi,

Looks very interesting! But, maybe you forgot the source subdirectories?

**Comment by tomek-he-him** [comment]
Hi, and thanks for the thumbs up! :)

I actually haven’t had the time to do anything here except for stubbing the readme. The project for which this was planned shot forward and there was no time to care about XML formatting :(

This is definitely something I’m going to go back to though – as long as a good alternative doesn’t crop up in the meantime.

I’ll update the readme too.
